### ISSUE TITLE
Error al ejecutar todos los tests desde una carpeta

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-lsp-ide#101]
Al hacer Run All Tests tira

```
 *  Executing task:  test --skipValidations -p /home/dodain/workspace/wollok-2023/tp-objetos-starship2 
/usr/bin/bash: line 1: test: -p: binary operator expected
```

Si se ejecuta "Run test" en forma individual con el plugin de Jest eso tira:

```
 *  Executing task:  test 'testBiblioteca."Test de Patricia"."Cuando no esta de humor y para el libro cuidadoConElPerro"' --skipValidations -p /home/dodain/workspace/wollok-2023/tp-objetos-starship2 
/usr/bin/bash: line 1: test: syntax error: `--skipValidations' unexpected
```

![image](https://github.com/uqbar-project/wollok-lsp-ide/assets/4549002/0cbc830a-4d92-43e1-be6f-e761da5d4959)

**Comment by PalumboN** [comment]
@fdodino tenías configurado el path a CLI? Parece como que hay un path vacío... quizá falte un test de que falle si querés usar algo con el CLI pero no le pasaste un path??

**Comment by fdodino** [comment]
@PalumboN , el path lo tengo configurado. El problema para mí tiene que ver con el mismo tema de que estoy tratando de ejecutar tests en un proyecto que es distinto de donde tengo wollok-lsp-ide. Si ejecuto los tests dentro de una carpeta hermana de wollok-lsp-ide funciona:
![image](https://github.com/uqbar-project/wollok-lsp-ide/assets/4549002/eee8b2d6-4356-428b-8b32-5e5dd0d4d53d)

Incluso me anda el `Run test` desde el plugin de Jest.

El proyecto está en

```
+ workspace
   + wollok-dev
      + wollok-workspace
      + wollok-lsp-ide
```

Cuando voy a otra carpeta

```
+ workspace
   + wollok-dev
      + wollok-lsp-ide
   + wollok-2023
      + proyecto-de-alumnes <-- acá
```

Se me rompe.

**Comment by fdodino** [comment]
Lo mismo me pasa con el REPL en ese workspace:

```
 *  Executing task:  test --skipValidations -p /home/dodain/workspace/wollok-2023/tp-objetos-wollokers 

/usr/bin/bash: line 1: test: -p: binary operator expected

 *  The terminal process "/usr/bin/bash '-c', ' test --skipValidations -p /home/dodain/workspace/wollok-2023/tp-objetos-wollokers'" failed to launch (exit code: 2). 
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task:  repl /home/dodain/workspace/wollok-2023/tp-objetos-wollokers/src/people.wlk --skipValidations -p /home/dodain/workspace/wollok-2023/tp-objetos-wollokers 

/usr/bin/bash: line 1: repl: command not found

 *  The terminal process "/usr/bin/bash '-c', ' repl /home/dodain/workspace/wollok-2023/tp-objetos-wollokers/src/people.wlk --skipValidations -p /home/dodain/workspace/wollok-2023/tp-objetos-wollokers'" failed to launch (exit code: 127). 
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by fdodino** [comment]
AAAAAAAHHHH!

El tema es que cada vez que cambio de carpeta, tengo que volver a setear la variable de entorno de wollok-ts-cli. Teníais razón!!!

![image](https://github.com/uqbar-project/wollok-lsp-ide/assets/4549002/cc085963-e225-4a2f-87c4-9fb804128932)

**Comment by fdodino** [comment]
![image](https://github.com/uqbar-project/wollok-lsp-ide/assets/4549002/6ada17c2-9ac3-4d64-98e2-16eabccde6cb)

@PalumboN ahí me anduvo. Solo creo que estaría bueno tirar un error diciendo: "te falta agregar la referencia a wollok-ts-cli".

**Comment by fdodino** [comment]
@PalumboN , qué te parece?

![image](https://github.com/uqbar-project/wollok-lsp-ide/assets/4549002/2e63e5ad-bfab-48ba-85f3-519088a1a527)

**Comment by PalumboN** [comment]
Jajaja excelente! 🤩
