### ISSUE TITLE
Problemas en la última versión

### ISSUE THREAD

**Issue by liamwilk** [uqbar-project/wollok-lsp-ide#112]
Buenas 👋

Quería comentarles que en la última versión disponible de wollok-lsp-ide (0.1.1, actualizado via el marketplace de VS Code) no está funcionando correctamente el Linter, adjunto captura de pantalla de lo que muestra el apartado Output: 

![Untitled](https://github.com/uqbar-project/wollok-lsp-ide/assets/33577925/828b7e81-faa6-4383-a733-76703409c245)

Pero si vuelvo a la versión 0.1.0, el Linter vuelve a funcionar y el apartado de Output muestra las métricas de performance bien. Les comento que el error me sucede en Windows, en Linux aún no probé si está el mismo problema. 

Desde ya, muchisimas gracias y aprovecho para comentarles que está muy buena está versión de Wollok!

**Comment by PalumboN** [comment]
Buenas @liamwilk , muchas gracias por reportar! :)

Efectivamente, hay un error en el server, el output completo es
```bash
node:internal/modules/cjs/loader:1132
  throw err;
  ^

Error: Cannot find module 'vscode-languageserver-textdocument'
Require stack:
- /Users/palumbon/.vscode/extensions/uqbar.wollok-lsp-ide-0.1.1/server/out/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1129:15)
    at Module._load (node:internal/modules/cjs/loader:974:27)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1195:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/palumbon/.vscode/extensions/uqbar.wollok-lsp-ide-0.1.1/server/out/server.js:3:46)
    at Module._compile (node:internal/modules/cjs/loader:1316:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
    at Module.load (node:internal/modules/cjs/loader:1171:32)
    at Module._load (node:internal/modules/cjs/loader:1012:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/palumbon/.vscode/extensions/uqbar.wollok-lsp-ide-0.1.1/server/out/server.js'
  ]
}

Node.js v18.15.0
[Info  - 19:41:05] Connection to server got closed. Server will restart.
[Error - 19:41:05] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 19:41:05] Wollok client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/modules/cjs/loader:1132
  throw err;
  ^
```

Reintenta conectarse 5 veces y muere, por lo tanto nunca se inicia ningún servicio 👎

Al parecer no encuentra `vscode-languageserver-textdocument`.

El `package.json` [se tocó para publicar en el Marketplace](https://github.com/uqbar-project/wollok-lsp-ide/commit/0716bf25714d8ac47fdb52078a4e1de1397ec664#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) tal vez esté relacionado con eso? Un problema de versiones? Falta updatear/ agregar [alguna dependencia](https://www.npmjs.com/package/vscode-languageserver-textdocument)?

**Comment by fdodino** [comment]
Eso, gracias @liamwilk , ya lo pude reproducir en otra máquina, vamos a estar haciendo un release nuevo próximamente para corregirlo.

**Comment by fdodino** [comment]
@PalumboN , el problema está en el [archivo .vscodeignore](https://github.com/uqbar-project/wollok-lsp-ide/commit/0716bf25714d8ac47fdb52078a4e1de1397ec664#diff-0a721cd4753ff50bbbe1237397c3c7692080254fa766268fcc8b05ef633c50bf), ahí se definen las dependencias que van al bundle publicado en el release. No estoy seguro y ahora no estoy en mi máquina wollokera, pero el .VSIX no debe tener la dependencia al vscode del server que necesita. Hay que descargar ambos VSIX (el de la versión 0.1.0 y el de la 0.1.1) y fijarse cuál es la dependencia en el directorio server que está en la primera y no en la segunda, y chequear que no la ignore `.vscodeignore`. Ya me anoté para verlo en la épica.

**Comment by fdodino** [comment]
Ahí lo detecté @PalumboN : 

<img width="510" alt="image" src="https://github.com/uqbar-project/wollok-lsp-ide/assets/4549002/d22ce5a4-a163-48b3-8072-4bd9cbf00275">

Es la [línea 9](https://github.com/uqbar-project/wollok-lsp-ide/commit/0716bf25714d8ac47fdb52078a4e1de1397ec664#diff-0a721cd4753ff50bbbe1237397c3c7692080254fa766268fcc8b05ef633c50bf) del `package.json`, no tendría que haberle puesto que ignore `**/node_modules/**` , porque eso hizo que no se metiera `vscode-languageserver-textdocument` dentro de los node_modules.

**Comment by fdodino** [comment]
Hola @liamwilk ! Fijate si la nueva versión (0.1.2) trae solucionado este inconveniente. Yo ya lo probé en una Mac del trabajo y anduvo ok. Gracias y abrazo!

**Comment by liamwilk** [comment]
Buenas @fdodino 👋

Recién probé la nueva versión de la extensión en Linux y funciona perfecto!!
