### ISSUE TITLE
Dependencia ente plugins

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-lsp-ide#113]
@fdodino dijo:

> ahí investigando en el package.json de wollok-lsp-ide (el raíz) se puede agregar:
> ```json
>   "extensionDependencies": [
>     "Orta.vscode-jest",
>     "uqbar.wollok-highlight"
>   ],
> ```
> pero la verdad no me convence, porque sin estas extensiones wollok-lsp-ide funciona. Entonces lo que preferí hacer es toquetear el README del release que viene.

-----

Para mí no deberíamos depender de `jest`, en mi cabeza tanto ellos como nosotros deberíamos usar la misma API del VSCode.

Sí instalaría el highlight también, así es más simple la instalación:
1. Te descargas Wollok con un script (CLI)
2. Te descargas la extensión en el VSCode
3. Listo :)

**Comment by fdodino** [comment]
Ok, dale, hasta que salga el highlight basado en el AST que idealmente ya debería formar parte de wollok-lsp-ide.
:)

**Comment by fdodino** [comment]
uh, al tratar de hacerlo eso rompe los tests e2e:

![image](https://github.com/uqbar-project/wollok-lsp-ide/assets/4549002/d6d182f7-7092-4ec6-8efb-8aa0ef074592)

**Comment by fdodino** [comment]
Por ahora lo dejé standby, teniendo en cuenta que vamos a integrarle el highlighter del AST
