### ISSUE TITLE
El VSIX pesa más del doble en la versión 0.1.2

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-lsp-ide#115]
Venía pesando 1,97MB y en la versión 0.1.2 pesa 5MB. Posiblemente tenga que ver con node_modules que no se ignoraron, hay que tener cuidado porque algunas dependencias como las de vscode son necesarias. Para tunearlo con tiempo, nada urgente.

**Comment by fdodino** [comment]
Para quien quiera verlo, se puede probar localmente haciendo

```bash
npm i -g vsce
```

y luego publicando el .VSIX local:

```bash
vsce package
```

El .VSIX es un archivo comprimido al igual que un .jar de Java o un .tar.gz, .zip, etc. Se puede abrir con cualquiera de esos programas y se puede tunear desde el archivo `.vscodeignore`. Luego hay que probarlo localmente instalando el .VSIX, como se cuenta en [la página de la wiki, solamente la parte de package](https://github.com/uqbar-project/wollok-lsp-ide/wiki/Package-and-Deploy).

**Comment by ivojawer** [comment]
a partir de #179 ahora bundlea la extension, asi que esto ya no haria falta
