### ISSUE TITLE
Inactivar el diagrama en el ts-cli si no querés activarlo

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-lsp-ide#122]
wollok-ts-cli incorporó la posibilidad de pasarle un parámetro: `--noDiagram` si no lo querés activar. Que eso se agregue a la configuración (por defecto que esté activado) y que en ese caso no se levante el navegador.

**Comment by fdodino** [comment]
El parámetro es `--skipDiagram`

**Comment by PalumboN** [comment]
Pregunta tangencial: hay una forma de abrir el diagrama una vez que lo cerré? (En el IDE).

Lo cerré y no tengo forma de volver a levantarlo :P

**Comment by fdodino** [comment]
Sí, `F1`: `>Simple Browser Show`

![image](https://github.com/uqbar-project/wollok-lsp-ide/assets/4549002/fc861346-b739-401e-a5df-d7bf45406029)

y después pedís `localhost:3000`
