### ISSUE TITLE
Ejecutar un game vs. ejecutar un programa

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-lsp-ide#123]
No estoy seguro de si deberíamos tener dos comandos diferentes o que se de cuenta solo en base a que esté usando el object game.

**Comment by PalumboN** [comment]
Para mí el juego se debería levantar al hacer `game.start()`, que es como lo hace Xtext. 
Eso serviría tanto para programas como para el REPL ;)

**Comment by fdodino** [comment]
El tema @PalumboN es que si es un game levantamos el server... salvo que pongamos un listener a escuchar el evento start() del objeto game, yo me imaginaría que tenemos que inspeccionar el código del programa para ver si se está enviando un mensaje start() a game...

**Comment by fdodino** [comment]
@PalumboN yo creo que este issue ya se puede cerrar y podemos pensar el runner interactivo en otro issue
