### ISSUE TITLE
Verificar que cuando se rompe el parser se esté atrapando la excepción y no salte el popup

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-lsp-ide#124]
Hoy aparece este error

[Error - 11:53:27 PM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: No source map found for node
  Code: -32603 

pero además suele saltar cada tanto un molesto popup. Lo que tiene que pasar es que tiene que recuperarse en el primer nodo que pueda y marcar el resto como malformed entity o malformed algo.

**Comment by PalumboN** [comment]
Ahora no salta ningún popup y se marca con error todo el archivo:
<img width="613" alt="image" src="https://github.com/uqbar-project/wollok-lsp-ide/assets/4098184/d59edff1-2826-4016-a1bd-2547dbdf71af">

Se cierra issue?

**Comment by fdodino** [comment]
Dale! Lo cierro! En algún momento me voy a sentar a tratar de romper Wollok LSP IDE y ver que responda bien (onda: que loguee el error y que no aparezcan popups molestos)
