### ISSUE TITLE
Si Wollok CLI ya se encuentra en en PATH no pedir que se configure

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-lsp-ide#128]
Si Wollok CLI ya se encuentra en el path entonces los comandos pueden hacer directamente `wollok blah` y no sería necesario configurar el directorio

**Comment by fdodino** [comment]
@PalumboN , el tema es que

- el ejecutable por defecto que se genera es wollok-ts-cli o wollok-ts-cli.exe
- tendríamos que hacer algo como `whereis wollok` asumiendo que la persona que lo instaló renombró el ejecutable a wollok.  En Windows existe el [where](https://superuser.com/questions/21067/windows-equivalent-of-whereis) pero me parece medio overkill para algo que puede setear un usuarie.

**Comment by PalumboN** [comment]
Lo que yo tenía en mente es tener un bash `install-wollok.sh` que te descarga la última cli para tu SO y lo pone en un lugar específico con un nombre específico (wollok) y además lo agrega al path.

Después el IDE podría fijarse directamente ahí o tenerlo en la config cómo default.

**Comment by fdodino** [comment]
![image](https://github.com/uqbar-project/wollok-lsp-ide/assets/4549002/38f2324d-fb24-43a0-ad62-1967db71d556)

Me gusta fuerte!

**Comment by PalumboN** [comment]
Ahora podemos instalar wollok cli haciendo:
```bash
npm i -g wollok-ts-cli
```

Y ya deja el alias de `wollok` en la consola. 

Así que podemos dejar como config por default `wollok`, como dice en [el sition de instalación](https://uqbar-project.github.io/website-wollok-ts/getting_started/installation/#configuraci%C3%B3n)
