### ISSUE TITLE
Go to definition: falla con Annotations

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-lsp-ide#131]
Si se quiere ir a la definición de una annotation el LSP rompe y tira este error:

```
[Error - 23:08:09] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: No source map found for node
  Code: -32603 
```

**Comment by PalumboN** [comment]
Ahora no está rompiendo, tira un cartelito. Creo que sería el compotamiento esperado:
<img width="389" alt="image" src="https://github.com/uqbar-project/wollok-lsp-ide/assets/4098184/d812ca3e-120b-4e32-bb5e-47a238bcf74d">

Se cierra el issue?

**Comment by ivojawer** [comment]
Me parece bien
