### ISSUE TITLE
Diagnostics se pisan al revalidar el contenido

### ISSUE THREAD

**Issue by ivojawer** [uqbar-project/wollok-lsp-ide#138]
Los diagnostics que no provienen de la validacion del environment (por ahora solo existen los [errores del archivo](https://github.com/uqbar-project/wollok-lsp-ide/blob/82f610d01dded5b4680b460dd6ed40b494773b01/server/src/linter.ts#L128-L153)) deberían mantenerse entre revalidaciones.

Ahora al revalidar un archivo se pisan los diagnostics de todos los archivos del workspace: https://github.com/uqbar-project/wollok-lsp-ide/blob/82f610d01dded5b4680b460dd6ed40b494773b01/server/src/linter.ts#L80-L83

**Comment by PalumboN** [comment]
Esto creo que está solucionado en el último release (v0.2.1).

Podés checkear @ivojawer ? No recuerdo cómo reproducirlo.

**Comment by fdodino** [comment]
No recuerdo que pasara la última vez que estuve toqueteando la solapa problems, cierro el issue y cualquier cosa lo volvemos a abrir más adelante.
