### ISSUE TITLE
No considerar enters para mostrar problems

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-lsp-ide#14]
Hoy está marcando el error desde que comienza el nodo hasta que empieza el nodo siguiente:

![image](https://user-images.githubusercontent.com/4549002/146675098-19cbd427-c6ae-4b0f-b812-cd8b3f5f2317.png)

Deberíamos ignorar los enters, espacios y tabs para que no quede raro el reporte.

**Comment by fdodino** [comment]
En realidad, probaria como workaround no considerar el último Enter.

**Comment by PalumboN** [comment]
Para mí, si es para subrayar, haría un trim de todos los caracteres invisibles al momento de calcular el rango para el VSCode

**Comment by ivojawer** [comment]
Probandolo un poco no es tan consistente el error, por ejemplo aca depende de si el value de la asignacion es una lista o no

<img width="341" alt="image" src="https://github.com/uqbar-project/wollok-lsp-ide/assets/18614957/8f8b24a5-b2b4-442f-b908-acdb982cf8c2">
