### ISSUE TITLE
Renombrar un archivo con errores deja Problems zombies

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-lsp-ide#149]
Tenía 2 packages con el mismo nombre:
```bash
- pepita.wlk
- pepita.wtest
```

Y renombre el test a -> `pepitaTest.wtest` -> y luego le fui agregando un número.

Este es el resultado en la tab de Problems:

<img width="673" alt="image" src="https://github.com/uqbar-project/wollok-lsp-ide/assets/4098184/6eaa9354-d1a2-4316-879d-ee51f95c04a5">

Los problemas de archivos que ya no existen (con el nombre viejo) quedan por siempre.

**Comment by PalumboN** [comment]
Creo que habría que tocar esta función (que dispara cada vez que se renombra o elimina un archivo) para que limpie todo los Problems antes de volver a validar los documents.

**Comment by fdodino** [comment]
Efectivamente, venía complicado el tema porque la API de VSC está mal diseñada, no tiene un método para hacer un resetDiagnostics y te obligan a que vos te encargues de manejar todo con un solo método `setDiagnostics({ uri, diagnostics })`. Para colmo, el método `documents.keys()` que te devuelve la lista de los archivos de un proyecto, con el rename se trula un poco y te devuelve tanto el archivo antes de renombrar como el nuevo, por eso te quedan los problemas zombies.

La forma en que finalmente logré resolverlo fue meter un setTimeout, para asegurarme que
- primero: el cliente le manda el nombre del archivo antes de ser renombrado (el viejo). En realidad le manda la lista de archivos porque soportaría un rename masivo.
- segundo: el server recibe y parsea la lista de uris y espera a que se generen los diagnostics (problemas) de cada archivo
- tercero: mandamos un setTimeout para forzar una actualización asincrónica que demore, y de esa manera una vez que corrió el validate de cada archivo se elimina el de la uri vieja

Bastante choto el comportamiento de este componente de VCS, me hizo extrañar bocha al Eclipse que los centennials tanto bardean.

**Comment by PalumboN** [comment]
> Para colmo, el método `documents.keys()` que te devuelve la lista de los archivos de un proyecto, con el rename se trula un poco y te devuelve tanto el archivo antes de renombrar como el nuevo, por eso te quedan los problemas zombies.

Claro, por eso proponía borrar todos los diagnostics (mandar una lista vacía) de todos los archivos registrados (incluyendo viejos y nuevos) antes de re-validar. 
Luego el validador debería solamente crear diagnostics para los archivos que tienen un nodo asociado, así que el viejo no me importa si queda ahí. 

Después se podría implementar algo para limpiarlo, si es que molesta. Pero yo trataría de evitar los timeouts.

**Comment by fdodino** [comment]
> > Para colmo, el método `documents.keys()` que te devuelve la lista de los archivos de un proyecto, con el rename se trula un poco y te devuelve tanto el archivo antes de renombrar como el nuevo, por eso te quedan los problemas zombies.
> 
> Claro, por eso proponía borrar todos los diagnostics (mandar una lista vacía) de todos los archivos registrados (incluyendo viejos y nuevos) antes de re-validar. Luego el validador debería solamente crear diagnostics para los archivos que tienen un nodo asociado, así que el viejo no me importa si queda ahí.
> 
> Después se podría implementar algo para limpiarlo, si es que molesta. Pero yo trataría de evitar los timeouts.

Solo podés borrar los diagnostics si le pasás la lista de keys. Y no tenés forma de conocer los keys la primera vez, de todas las opciones el timeout (que solo encola el laburo de recrear los diagnostics) fue lo que mejor anduvo.
