### ISSUE TITLE
Traducción shouldMatchSuperclassReturnValue

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-lsp-ide#177]
Dice "valor del tipo devuelto..." Yo diría algo más explícito:

- _Este método retorna un valor pero el método que sobreescribe de la superclase no._
- _Este método no retorna valor pero el método que sobreescribe de la superclase sí._

**Comment by fdodino** [comment]
Ah, @Palumbo, pero para saber eso tengo que abrir el validador en dos.

Yo diría algo como "El método que sobreescribe la subclase debe respetar el mismo tipo que el método de su superclase (sea un método que solo produce efecto o que devuelve un valor)."

**Comment by PalumboN** [comment]
Ahh yo pensaba de que ese dato venga como param value del mensaje. O también de podría chismear el nodo con el error 🤔

Igual no me calienta, el mensaje que propones ya resuelve el issue :)

**Comment by fdodino** [comment]
Cierro el issue ahora que mergeamos todo
