### ISSUE TITLE
Go to definition en una send a un metodo generado por una property falla

### ISSUE THREAD

**Issue by ivojawer** [uqbar-project/wollok-lsp-ide#181]
Ejemplo minimo: 

```
object pepita {
 var property energia = 100
}

object manolo {
   method energiaDePepita() = pepita.energia()
}
```

Si quiero hacer navegar a la definicion de `pepita.energia()` me va a tirar un error diciendo 
```
[Error - 12:08:35 AM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: No source map found for node
  Code: -32603 
```

Lo cual es correcto pero esperaria que el LSP se de cuenta que es una property y la navegacion que me ofrezca sea navegando a la variable

**Comment by PalumboN** [comment]
Duplicated https://github.com/uqbar-project/wollok-lsp-ide/issues/50
