### ISSUE TITLE
Disponibilidad en Open Vsx

### ISSUE THREAD

**Issue by phosph** [uqbar-project/wollok-lsp-ide#184]
Sería muy útil contar con esta extensión disponible en el repositorio OpenVsx (default en vscodium), para no depender de los repositorios de Microsoft.

https://open-vsx.org/

**Comment by phosph** [comment]
hay un pedido similar en el repo del highlight https://github.com/uqbar-project/wollok-highlight-vscode/issues/8

**Comment by fdodino** [comment]
Hoy publicamos ambos vsix para descargar, el highlighter lo hizo bastante rápido pero lamentablemente wollok-lsp-ide está tardando y dado que se hace asincrónicamente no tengo forma de saber si lo está procesando o quedó encolado:

**Comment by fdodino** [comment]
Ya se publicó @phosph !

https://open-vsx.org/extension/uqbar/wollok-lsp-ide

Ahora tenemos que agregar las instrucciones en la wiki.

**Comment by phosph** [comment]
thanks @fdodino!!
