### ISSUE TITLE
Configurar puertos

### ISSUE THREAD

**Issue by joaqulopez** [uqbar-project/wollok-lsp-ide#186]
Poder configurar fácilmente en que puerto arrancar Run Repl
Está seteado en Port:3000 y lo quiero cambiar a Port:4000

**Comment by fdodino** [comment]
@PalumboN -> no me acuerdo en qué contexto le pasaba a alguien en la facu y pedí que cargara un issue, no se si fuiste vos @joaqulopez o no pero gracias porque me había olvidado.

Lo pongo como good first issue.

**Comment by fdodino** [comment]
Hay que agregar el parámetro en los settings y usarlo en el command que dispara el REPL.

**Comment by joaqulopez** [comment]
> @PalumboN -> no me acuerdo en qué contexto le pasaba a alguien en la facu y pedí que cargara un issue, no se si fuiste vos @joaqulopez o no pero gracias porque me había olvidado.
> 
> 
> 
> Lo pongo como good first issue.

Hola profe, si yo te había comentado que tenía ese problema porque el puerto 3000 lo tengo ocupado por un emulador de IBM Z

**Comment by fdodino** [comment]
ahí estuve jugando y lo agregué, me costó porque al introducir espacios me quiere escapear una comilla simple y me rompe cuando quiere disparar

![Uploading portNumberConfigurable.gif…]()
