### ISSUE TITLE
Analizar una forma de empaquetar la solución Wollok LSP IDE

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-lsp-ide#27]
Investigar de qué manera conviene empaquetar el proyecto Wollok LSP IDE:

- plugin solo
- plugin + VSC para atarlo a una versión
- otras

**Comment by fdodino** [comment]
@ivojawer @PalumboN ya que estamos con la publicación de releases, este ticket lo podemos dar por cerrado? Tenemos una forma ya estándar de empaquetar el proyecto?

**Comment by ivojawer** [comment]
Para los releases se empaqueta con
```bash
> npm run vscode:prepublish
> npm run package
```

Y eso escupe el .vsix, lo que no se es si eso archivo sirve para publicar la extensión.

**Comment by PalumboN** [comment]
Así es, eso se explica en la wiki https://github.com/uqbar-project/wollok-lsp-ide/wiki/Package-and-Deploy

Pero dejé el issue abierto porque en realidad estaría bueno subirlo al marketplace...

**Comment by fdodino** [comment]
Ya lo bajé a 260KB y dejé la [versión en el último release](https://github.com/uqbar-project/wollok-lsp-ide/releases/download/v0.1.0/wollok-lsp-ide-0.1.0.minimal.vsix), pero lamentablemente me tira 

```
 INFO  Publishing 'uqbar.wollok-lsp-ide v0.1.0'...
 ERROR  TF400898: An Internal Error Occurred. Activity Id: 35d21072-d598-4ba9-b339-cd1a5b52dc9d.
```

cada vez que quiero publicarlo. Mandé un mail a vscode @ marketplace . com , veremos si me contestan porque con ese mensaje críptico no se puede saber nada. Instalé localmente y me funcionó ok.

**Comment by fdodino** [comment]
> Así es, eso se explica en la wiki https://github.com/uqbar-project/wollok-lsp-ide/wiki/Package-and-Deploy
> 
> Pero dejé el issue abierto porque en realidad estaría bueno subirlo al marketplace...

Oki, ayer creé un ticket específico para eso, cierro este ticket porque ya definimos la forma en que empaquetamos el producto (al menos la tuneamos)
