### ISSUE TITLE
Migrar mensajes de validaciones de XText a lsp-ide

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok-lsp-ide#28]
El objetivo es completar esto:

https://github.com/uqbar-project/wollok-lsp-ide/blob/5b15b617b948d56e66bf0e6926ab9b58519a7e96/server/src/reporter.ts#L12-L28

- [ ] Pensar qué vale la pena testear automáticamente de esto.
- [ ] Intentar hacer tests manuales (levantar el lsp-ide) para ver que todo esto anduvo bien.

- Tener en cuenta que probablemente esto cambie cuando implementemos https://github.com/uqbar-project/wollok-language/issues/139

Cosas que pueden servir para este issue:
- Input: los mensajes de XText [en inglés](https://github.com/uqbar-project/wollok/blob/dev/org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties) y [en español](https://github.com/uqbar-project/wollok/blob/dev/org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties)
- El checklist de Dodain [en un google doc](https://docs.google.com/spreadsheets/d/1OPqJEXTufnpD_H2Awenocv8XQbsTqpWVJX8VHv2KPkY/edit#gid=0) donde tiene mapeados los id de validaciones de XText con los de LSP-IDE.

**Comment by FerRomMu** [comment]
Creeeeo que ya puedo poner solved with #29 . Te arrobo por si esto tendría que haber quedado abierto que veas que lo estoy cerrando @asanzo .
