### ISSUE TITLE
Autocomplete con prioridad

### ISSUE THREAD

**Issue by ivojawer** [uqbar-project/wollok-lsp-ide#53]
En este caso esta claro que `comer` deberia ser la primera opcion en el autocomplete, para ello deberiamos asignarle prioridad a las recomendaciones bajo algun criterio.
![image](https://user-images.githubusercontent.com/18614957/218328169-aa0e60e7-20c3-427a-b75d-02a9a1ac2b1a.png)

**Comment by fdodino** [comment]
ahí estuve jugando un poco @ivojawer @PalumboN 

![autocompleteMessages](https://github.com/uqbar-project/wollok-lsp-ide/assets/4549002/cb1c6a06-c24d-4e5e-b271-e0af74d40202)

- saqué en un primer momento los métodos de los describes, ahora que lo pienso bien deberían estar si estás en el mismo archivo, per
- ordeno 1. por métodos que estén en el mismo archivo que donde estoy, 2. métodos que estén un archivo que no empiece con wollok, 3. wollok.lang, 4. wollok.lib, 5. wollok.game (me molestaba mucho los métodos del teclado a(), b(), etc. así que los mandé al final)
- vm.wlk y mirror.wlk por ahora los estoy filtrando
- también filtro los métodos `<apply>` y los chirimbolos del pedido de Alf en el #85 
- podría no mostrar métodos de Object, no se qué opinan

voy a ver si hay al más fino para hilar

**Comment by fdodino** [comment]
Dos cosas que pienso:

- por supuesto, con un type system es otro cantar, pero no es ahora el momento
- qué onda si la expresión la evaluamos como hace el REPL y le preguntamos al RuntimeObject cuál es su fqn. Con eso podríamos tener un autocomplete más copado.

**Comment by fdodino** [comment]
qué bueno que autocompleta con bjetos anónimos!
![image](https://github.com/uqbar-project/wollok-lsp-ide/assets/4549002/65151929-2c66-4040-bc0c-08d18b6610e4)

**Comment by fdodino** [comment]
y ya logré ponerle autocompletado de literales dentro del body, el tema era sacar el firstStableNode y buscar la última expresión. Pero no me conformé y fui por más: 
- arreglé para que se pueda autocompletar en cualquier parte del body (el que tire el primer error, que debería ser de parseo, se puede mejorar)
- también hice que autocomplete listas y sets
- y ya que estamos cualquier new
- no tuve las agallas para el send, pero eventualmente podríamos interpretar un send, quedarnos con el runtime object y de eso conseguir el fqn

![autocompleteMessagesPiola](https://github.com/uqbar-project/wollok-lsp-ide/assets/4549002/c93ceca7-43e3-43b9-ac1f-6d31a55e552a)
