### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by ivojawer** [uqbar-project/wollok-lsp-ide#56]

**Comment by fdodino** [comment]
[En esta página](https://github.com/microsoft/vscode/blob/main/extensions/typescript-language-features/src/languageFeatures/formatting.ts) hay un ejemplo de una implementación para Typescript.

**Comment by fdodino** [comment]
Y [acá](https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices) cuenta lo mínimo que necesitamos para arrancar, el tema supongo que sería poder asociar cada nodo del AST con el correspondiente formato que debe tener.

En Xtext esa parte estaba bastante bien diseñada (aunque a veces colisionaban especificaciones y era difícil de encontrar cuáles eran los nodos que chocaban). [Acá](https://github.com/uqbar-project/wollok/blob/dev/org.uqbar.project.wollok/src/org/uqbar/project/wollok/formatting2/WollokDslFormatter.xtend) quedó el código que podría usarse como base.

**Comment by fdodino** [comment]
ah, de paso encontré que @ivojawer ya había estado jugando: https://github.com/uqbar-project/wollok-lsp-ide/tree/formatter

Hay que ver si podemos cherry-pickear ese laburo (o rebasearlo, si es que se puede sin tardar 7 horas).

**Comment by ivojawer** [comment]
En esa branch habia quedado algo que no me gustaba mucho la dirección que tomo. Recien la pise (la deje con el nombre `writer`) con lo que estaba trabajando locamente, que tiene solo el cableado del LSP.

**Comment by ivojawer** [comment]
Al parecer la implementacion del [formatter en typescript](https://github.com/microsoft/TypeScript/blob/61a96b1641abe24c4adc3633eb936df89eb991f2/src/services/formatting/formatting.ts) esta en el repo de ts y no el de la extensión de vscode 🤷
