### ISSUE TITLE
Document symbols cuando se inicializa el server

### ISSUE THREAD

**Issue by ivojawer** [uqbar-project/wollok-lsp-ide#61]
Cuando levanta el proyecto la request de los document symbols generalmente llega antes de que se construya el Package, causando un error cuando se quieren calcular estos.

**Comment by ivojawer** [comment]
Se implemento un fix a medias aca:
https://github.com/uqbar-project/wollok-lsp-ide/blob/ddc50250c6c6dd9eab786e6f3a2ef2ed667454f8/server/src/linter.ts#L159-L162

Pero esto lo unico que evita es que se muestre el error, lo que habria que hacer es esperar a que se termine de buildear el environment para responder.

**Comment by PalumboN** [comment]
Pasa algo similar con las completions al tener un archivo vacío y comenzar a escribir código.

Sospecho que necesitamos pensarlo mejor para que esos errores de "estoy buildeando, bancá que termine" no lleguen al usuario

**Comment by ivojawer** [comment]
Solved in #79
