### ISSUE TITLE
Se instancian multiples procesos que nunca se cierran al correr tests

### ISSUE THREAD

**Issue by ivojawer** [uqbar-project/wollok-lsp-ide#66]
Estuve jugando un rato con el CLI corriendo tests y cada corrida abre ~3 procesos que nunca se terminan, incluso cuando cierrola terminal y el VSCode (ventana y matando directamente el proces)

![image](https://user-images.githubusercontent.com/18614957/229365353-e7773dac-326a-4c2d-8ab6-32c673b64c14.png)

**Comment by PalumboN** [comment]
Esto estaría resuelto cuando saquemos Electron de CLI

**Comment by PalumboN** [comment]
Closed via https://github.com/uqbar-project/wollok-ts-cli/issues/51
