### ISSUE TITLE
Filtro de los tests no andan en Windows

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-lsp-ide#67]
Por lo que estuvimos investigando con @ivojawer es por un tema de comillas `" '` en el armado del comando que tira al CLI

**Comment by ivojawer** [comment]
Ahora al querer correr el test _"something"_ 

![image](https://user-images.githubusercontent.com/18614957/232328984-b0a30d5f-18a3-4de5-8a84-55ab20202ef1.png)

El comando generado es:
```cmd
<cli-path>\wollok-ts-cli-win.exe test 'tests."tests de pepita"."something"' -p <project-path>\pepita-main\src
```


Para que matchee correctamente el test en windows deberia ser:

```cmd
<cli-path>\wollok-ts-cli-win.exe test 'tests.\"tests de pepita\".\"something\"' -p <project-path>\pepita-main\src
```

**Comment by ivojawer** [comment]
Mas pruebas en Windows:
Se encontro que depende de la terminal (cmd, bash, powershell, etc) porque cada una tiene sintaxis distinta para los caracteres especiales

### Bash
```bash
~/Desktop/wollok-ts-cli-win.exe test 'tests."tests de pepita"."something else"' --skipValidations -p ~/Desktop/PRUEBA-WOLLOK-LSP/pepita-main/src
```
- Funciona completamente 😄 
- Atención a los paths que tiene que ser con forma de unix


### PowerShell
```powershell
C:\Users\Ivan\Desktop\wollok-ts-cli-win.exe test 'tests.\"tests_de_pepita\".\"something_else\"' -p C:\Users\Ivan\Desktop\PRUEBA-WOLLOK-LSP\pepita-main\src
```
- Tiene problemas con espacio, hay que cambiarlos por otro caracter en el proyecto
   - https://stackoverflow.com/questions/6714165/powershell-stripping-double-quotes-from-command-line-arguments
   - https://stackoverflow.com/questions/6224638/powershell-call-msbuild-with-nested-quotation-marks
   - TLDR: PowerShell hace cosas raras con las comillas dobles cuando son usadas en un string que se pasa como argumento de un ejecutable 😭 

### CMD 
```cmd
C:\Users\Ivan\Desktop\wollok-ts-cli-win.exe test "tests.\"tests de pepita\".\"something else\"" -p C:\Users\Ivan\Desktop\PRUEBA-WOLLOK-LSP\pepita-main\src
```
- Funciona completamente 😄 
- Tema comillas
   - El filtro hay que pasarlo entre ""
   - Las comillas que matchean en el AST van escapeadas con `\`

**Comment by ivojawer** [comment]
En Windows con default profile: Git Bash


```
 *  Executing task: C:\Users\Ivan\Desktop\wollok-ts-cli-win.exe repl c:\Users\Ivan\Desktop\PRUEBA-WOLLOK-LSP\pepita-main\src\example.wlk --skipValidations -p c:\Users\Ivan\Desktop\PRUEBA-WOLLOK-LSP\pepita-main 

bash: C:UsersIvanDesktopwollok-ts-cli-win.exe: command not found

 *  The terminal process "C:\Program Files\Git\bin\bash.exe '--login', '-i', '-c', 'C:\Users\Ivan\Desktop\wollok-ts-cli-win.exe repl c:\Users\Ivan\Desktop\PRUEBA-WOLLOK-LSP\pepita-main\src\example.wlk --skipValidations -p c:\Users\Ivan\Desktop\PRUEBA-WOLLOK-LSP\pepita-main'" terminated with exit code: 127. 
 *  Terminal will be reused by tasks, press any key to close it. 
```
