### ISSUE TITLE
Soportar renames

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-lsp-ide#73]

**Comment by fdodino** [comment]
Esto ya está, no @PalumboN ? Lo podemos cerrar?

![rename](https://github.com/uqbar-project/wollok-lsp-ide/assets/4549002/42b58e73-07ac-44e0-95da-6ce18a9dc6e2)

**Comment by PalumboN** [comment]
Sí, después podemos armar otros con los features que falten
