### ISSUE TITLE
Evitar el autocomplete de mensajes en los imports

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-lsp-ide#74]
Al poner el punto me autocompleta con mensajes (?

<img width="809" alt="image" src="https://github.com/uqbar-project/wollok-lsp-ide/assets/4098184/610d991b-1bd2-4557-9113-eaf8668ee0dd">

Estaría bueno que sugiera en base a la estructura del AST

**Comment by fdodino** [comment]
Cierro el ticket porque ya fue mergeada la épica.
