### ISSUE TITLE
Error incorrecto: "Debe implementar todos los métodos abstractos heredados" cuando falta el cuerpo del método

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok-lsp-ide#84]
- [ ] Cuando falta el cuerpo de un método de un objeto o una clase sin subclases el error debería ser "Falta el cuerpo del método" y no "Debe implementear todos los métodos abstractos heredados"
![image](https://github.com/uqbar-project/wollok-lsp-ide/assets/5421992/05e38428-f5a3-4e69-b3e9-a3be9ab690db)

- [ ] Está también esta versión del error, cuando falta el "=":
![image](https://github.com/uqbar-project/wollok-lsp-ide/assets/5421992/f109379f-10a6-492a-9c49-aed7841bb2c5)

**Comment by fdodino** [comment]
Este issue hay que resolverlo en wollok-ts.

**Comment by fdodino** [comment]
Respecto al método con el `=`@asanzo, eso ahora rompe el parser:
![image](https://github.com/uqbar-project/wollok-lsp-ide/assets/4549002/7829335f-e56f-4cca-877f-4ea755c76ce6)

Así que yo lo dejaría así, al menos no tira el error de que debemos implementar métodos heredados.
