### ISSUE TITLE
Las sugerencias de mensajes, cuando escribí un punto, no deben incluir los chirimbolos

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/wollok-lsp-ide#85]
En este caso:

![image](https://github.com/uqbar-project/wollok-lsp-ide/assets/5421992/27be3f8b-4758-426f-b194-f7a3e0fbb6ab)

Estaría bueno que no ofreciera esos mensajes.

Oooooo que si le doy "enter", borre el punto.

**Comment by fdodino** [comment]
bueno, yo quería ir por lo segundo pero:

- la idea de redefinir el `range` no funcionó, autocompleta igual si usás `insertText`
- queriendo usar `textEdit` intente generar uno con `EditText.replace(range, replaceText)` que parecía ser la papa. Directamente rompía el autocompletado y no mostraba nada

Así que fui por filtrar los métodos sin chirimbolos, lo cual tiene sentido porque uno no escribe punto:

![image](https://github.com/uqbar-project/wollok-lsp-ide/assets/4549002/fcb17dd2-ab07-4603-b9b8-6e13f747aa3b)
