### ISSUE TITLE
[EPIC] - Poder ejecutar código desde el editor

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-lsp-ide#89]
Estaría bueno tener una forma de evaluar código desde el editor...

**Comment by guillep** [comment]
que smalltalkero

**Comment by fdodino** [comment]
Estaría bueno armar una especificación más concreta de cómo lograrlo: 

- casos felices (`new Bird()`, `2 + 2`) y otros más complicados (`a = 3` cuando no tengo la definición de a previamente). 
- cómo manejar la respuesta: lo escribo directamente en el editor, lo mando a la consola creando un programa...
- cómo manejar los errores

**Comment by PalumboN** [comment]
Esto era claramente siempre que se pueda evaluar (si hay dependencias "de afuera" no).

Igual la flashié, ya no quiero esto, prefiero un REPL más poderoso 😄
