### ISSUE TITLE
El spinner no desaparece si hay errores

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-lsp-ide#92]
Si Wollok falla al analizar el archivo (en el parser por ejemplo) entonces el spinner de "Building Wollok" no desaparece nunca.

**Comment by fdodino** [comment]
@PalumboN , lo cierro porque no lo pude reproducir, yo vi que hubo toques de @ivojawer.

![issueBuilding](https://github.com/uqbar-project/wollok-lsp-ide/assets/4549002/6b65125e-721c-4426-9c76-2e8f1fe6313c)
